### ISSUE TITLE
"Prefix" command is useless

### ISSUE THREAD

**Issue by TotallyTriggeredTigers** [goddyCodes/Branch#3]
We all know what the prefix is, it's in the playing field. You must've known the prefix to run a command in the first place. Unless you're gonna use JSON and make the prefix able to change, you should remove the command.

**Comment by Gitcodesoftware** [comment]
Assign a label goddy, you useless sack of shit

**Comment by goddyCodes** [comment]
Assigned invalid. Nigga.

**Comment by goddyCodes** [comment]
jk im gonna take it off, thanks for the advice.

**Comment by Gitcodesoftware** [comment]
If it's invalid, you need to close it. kthx
